bundle:
  name: olist-data-platform

variables:
  catalog:
    default: olist_lakehouse
  schema:
    default: default

targets:
  dev:
    default: true
    workspace:
      host: https://dbc-0856e78c-d501.cloud.databricks.com

resources:
  pipelines:
    olist_pipeline:
      name: "[${bundle.target}] Olist Medallion Pipeline"
      catalog: ${var.catalog}
      target: ${var.schema}
      serverless: true
      libraries:
        - file: ./src/pipelines/bronze
        - file: ./src/pipelines/silver

      # clusters:
      #   - label: default
      #     autoscale:
      #       min_workers: 1
      #       max_workers: 2

jobs:
  initial_setup:
    name: "[${bundle.target}] Olist Infrastructure Setup"
    tasks:
      - task_key: run_setup_scripts
        environment_key: Default
        spark_python_task:
          python_file: ./src/setup/run.py